import React from "react"
import styles from "@/styles/styles.module.css"
import { Input, Header, Button, TextArea, Form, Icon } from 'semantic-ui-react';
import { useRouter } from "next/router"
import Head from "next/head";

export default function Contact() {
  const [fullName, setFullName] = React.useState("")
  const [email, setEmail] = React.useState("")
  const [subject, setSubject] = React.useState("")
  const [message, setMessage] = React.useState("")
  // let fullName = "Mychal Wood"
  // let email = "mychwood@iu.edu"

  const router = useRouter()
  function contactFormSubmit(e) {
    e.preventDefault()
    if (fullName !== "" && email !== "" && subject !== "" && message !== "") {
      router.push("/contact/success")
    }
    console.log(fullName, email, subject, message)
  }

  function updateContactInfo(e) {
    console.log(e.currentTarget.name, e.currentTarget.value)
    if (e.currentTarget.name === "fullName") {
      setFullName(e.currentTarget.value)
    }
    if (e.currentTarget.name === "email") {
      setEmail(e.currentTarget.value)
    }
    if (e.currentTarget.name === "subject") {
      setSubject(e.currentTarget.value)
    }
    if (e.currentTarget.name === "message") {
      setMessage(e.currentTarget.value)
    }
  }

  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form className={styles.form} onSubmit={contactFormSubmit}>
        <Header as="h1">Contact Us</Header>
        <p>Feel free to use this form to get ahold of me!</p>
        <div className={styles.formField}>
          <label>Name:</label>
          <Input placeholder='Name:'>
    <input name='fullName' type="text"
            placeholder="Name:"
            onChange={updateContactInfo}
            value={fullName}
            required />
  </Input>
          <label>Email:</label>
          <Input placeholder='Email:'>
    <input name='email' type="email"
            placeholder="Email:"
            onChange={updateContactInfo}
            value={email}
            required />
  </Input>
          <label>Subject:</label>
          <Input placeholder='Subject:'>
    <input name='subject' type="text"
            placeholder="Subject:"
            onChange={updateContactInfo}
            value={subject}
            required />
  </Input>
          <label>Message:</label>
          <TextArea
            name="message"
            placeholder="Message:"
            onChange={updateContactInfo}
            value={message}
            required
          />
        </div>
        
        <div className={styles.formField}>
        <Button type='submit'>Submit <Icon name='send'/></Button>
        </div>
      </Form>
    </>
  )
}
