import React from "react"
import styles from "@/styles/styles.module.css";
import Head from 'next/head'
import { Grid, Header, Image} from 'semantic-ui-react';
export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid columns='1' verticalAlign="center">
        <Grid.Row columns={1}>
          <Grid.Column mobile={12} tablet={10} computer={8}><Header as='h1' textAlign="left">Home</Header></Grid.Column>
        </Grid.Row>
        <Grid.Row columns={1}>
          <Grid.Column mobile={12} tablet={10} computer={8}><Header as='h4' textAlign="left">Welcome to the Cat Database!</Header></Grid.Column>
        </Grid.Row>
        <Grid.Row columns={1}>
          <Grid.Column mobile={12} tablet={10} computer={8} textAlign="left">
          <p>
        Welcome to the cat database! Here you can find cats pulled from the cat database, and you can add them to a list of your favorites, as well as view some of the details about them!
      </p>
          </Grid.Column>
        </Grid.Row>
        <Grid.Row columns={1}>
          <Grid.Column mobile={12} tablet={10} computer={8}>
            <Image src="cat_example.jpg"/>
          </Grid.Column>
        </Grid.Row>
        <Grid.Row columns={1}>
          <Grid.Column mobile={12} tablet={10} computer={8}>
            <Image src="cat_example2.jpg" />
          </Grid.Column>
        </Grid.Row>
        </Grid>       
    </>
  )
}
